### ISSUE TITLE
Debugger Never Attaches

### ISSUE THREAD

**Issue by tmm08a** [SkyLined/cBugId#1]
I get this error when I attempt to attach to Edge (Win 10) with cdb. I have the following paths set:
-  Set cdb=C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe
-  Set BugId=C:\Users\test\Desktop\BugId-master\BugId-master\BugId.py

The relevant lines in EdgeBugId.cmd:
-  SET URL="http://127.0.0.1/testFile.php"
- SET BugIdArguments=

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\test\Desktop\BugId-master\BugId-master\modules\cBugId\cCdbWrapper.py", line 213, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "C:\Users\test\Desktop\BugId-master\BugId-master\modules\cBugId\cCdbWrapper.py", line 207, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "C:\Users\test\Desktop\BugId-master\BugId-master\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 117, in cCdbWrapper_fCdbStdInOutThread
    oCdbWrapper.nApplicationResumeDebuggerTime = fnGetDebuggerTime(oTimeMatch.group(1));
  File "C:\Users\test\Desktop\BugId-master\BugId-master\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 19, in fnGetDebuggerTime
    assert oTimeMatch, "Cannot parse debugger time: %s" % repr(sDebuggerTime);
AssertionError: Cannot parse debugger time: 'Tue Sep  6 22:33:10.098 2016 (UTC - 7:00)'
```

I've tried with different URLs, running it as admin, manually checking that cdb.exe was working at that path (it is). Not sure what else to try.

**Comment by 5uWPlrSD** [comment]
Thank you for the bug report and sorry for the trouble you had to go through!

The issue is quite simple: I failed to take into account negative offsets in timezones, "(UTC - 7:00)" in your case. The code was unable to pass the debugger time because it expected a "+" after "UTC".

I fixed this issue and I will upload the new code it in a few minutes, after I've run all unit-tests to make sure I've not introduced new bugs.

**Comment by SkyLined** [comment]
Thank you for the bug report and sorry for the trouble you had to go through!

The issue is quite simple: I failed to take into account negative offsets in timezones, "(UTC - 7:00)" in your case. The code was unable to parse the debugger time because it expected a "+" after "UTC".

I fixed this issue and I will upload the new code it in a few minutes, after I've run all unit-tests to make sure I've not introduced new bugs.

**Comment by tmm08a** [comment]
Awesome that did it. Thanks for the super fast turnaround :)!

**Comment by SkyLined** [comment]
Sorry for the delay, I am having some troubles with symbols thta delayed running the tests.

Anyway, this is the fix:
https://github.com/SkyLined/cBugId/commit/99eb81b90c79798a6de32ff180e39d4e96b3f25f

Let me know how BugId works out for you!
